name: System Configurations Helpers
description: Drible // Marketing Digital & Branding
footer-links:
  email: tiago.silva@drible.pt
  facebook: agenciadrible
  github: popperz0r/sys-config
  twitter: popperz0r
theme: jekyll-theme-cayman
